### PR TITLE
docs: add help center docs

### PR DESCRIPTION
**Pull request by uniyalabhishek**

### CODE REVIEW

**Comment by iSpeakNerd** [comment]
can we have headers be `Help Docs`, `Dev Docs`, and `Dev Tutorials`?

or merge tutorials as subset of dev docs so there's just 2 top-level choices

image

**Comment by kenny-io** [comment]
Nice work @uniyalabhishek 

Just a little orderliness needed on the navbar, here's my recommendation:

- Rename "Help Docs" to just “Help”. It's counter intuitive to have two "Docs" items.
- Move it forward so that it appears like this: Docs | Help | Tutorials (So we can present the dev docs as the first line item)

**Comment by iSpeakNerd** [comment]
> Nice work @uniyalabhishek
> 
> Just a little orderliness needed on the navbar, here's my recommendation:
> 
> * Rename "Help Docs" to just “Help”. It's counter intuitive to have two "Docs" items.
> * Move it forward so that it appears like this: Docs | Help | Tutorials (So we can present the dev docs as the first line item)

@kenny-io does tutorials include tutorials for creating TGRs? I'm a new user and that's where I'd look. 

hence my suggestion of putting `Help` and `Dev` in front of the names

**Comment by iSpeakNerd** [comment]
how about `User Guide` for Help?

where do the DAO documents (contract params, proposal model, miniapp dev process) go in your mind with this combination @kenny-io @uniyalabhishek?

**Comment by kenny-io** [comment]
> how about `User Guide` for Help?
> 
> where do the DAO documents (contract params, proposal model, miniapp dev process) go in your mind with this combination @kenny-io @uniyalabhishek?

All the DAO related documents are already available in the Help Docs section. I also like the idea of `User Guide` in place of `Help docs`

**Comment by kenny-io** [comment]
> 



> > Nice work @uniyalabhishek
> > Just a little orderliness needed on the navbar, here's my recommendation:
> > 
> > * Rename "Help Docs" to just “Help”. It's counter intuitive to have two "Docs" items.
> > * Move it forward so that it appears like this: Docs | Help | Tutorials (So we can present the dev docs as the first line item)
> 
> @kenny-io does tutorials include tutorials for creating TGRs? I'm a new user and that's where I'd look.
> 
> hence my suggestion of putting `Help` and `Dev` in front of the names

It encompasses all tutorials we'll write WRT all our products/services. The resource for creating TGRs already exist in the dev docs. Tutorials are helpful for more complex implementations that require more granular detail or nuances that are not covered in depth on the docs.

**Comment by iSpeakNerd** [comment]
> > 
> 
> > > Nice work @uniyalabhishek
> > > Just a little orderliness needed on the navbar, here's my recommendation:
> > > 
> > > * Rename "Help Docs" to just “Help”. It's counter intuitive to have two "Docs" items.
> > > * Move it forward so that it appears like this: Docs | Help | Tutorials (So we can present the dev docs as the first line item)
> > 
> > 
> > @kenny-io does tutorials include tutorials for creating TGRs? I'm a new user and that's where I'd look.
> > hence my suggestion of putting `Help` and `Dev` in front of the names
> 
> It encompasses all tutorials we'll write WRT all our products/services. The resource for creating TGRs already exist in the dev docs. Tutorials are helpful for more complex implementations that require more granular detail or nuances that are not covered in depth on the docs.

that doesn't answer my question. Is `Tutorials` exclusively dev tutorials, y/n? 
- if not exclusive to devs we should move all tutorials to that category (incl. content already in help docs) 
- if yes we should clarify that they are exclusively for devs with `Dev Tutorials` title

**Comment by iSpeakNerd** [comment]
from devrel sync today,

**Top level headers**
`Developers`, `Users`, `DAO` --> `Developers`, `Admins`, `Members`, `DAO` after Member Portal release

**Comment by kenny-io** [comment]
@uniyalabhishek do you want to implement the recent changes and update this PR?

**Comment by uniyalabhishek** [comment]
@kenny-io @iSpeakNerd updated this PR with discussed changes. let's merge it after discussing it with the team! we will also need to add redirects for help docs. dev docs urls will remain the same.

**Comment by kenny-io** [comment]
> 



> what do we need to do to ensure all links to old docs redirect to new locations?

We'll just need to setup redirects on the Help Docs hosted site. help.collab.land will still be available for the next month until until we've set up all necessary redirects and wind it down. In the meantime, I'll merge this update so we can start crawling the help docs.

**Comment by iSpeakNerd** [comment]
@kenny-io should i start making issues/PRs against the dev docs repo then? https://github.com/abridged/collabland-dev

**Comment by kenny-io** [comment]
> @kenny-io should i start making issues/PRs only against the dev docs repo then? https://github.com/abridged/collabland-dev

Yes, correct!

**Comment by uniyalabhishek** [comment]
We can also deploy this same content to help.collab.land since it's already deployed to multiple domains:
"docs.collab.land",
"doc.collab.land",
"dev.collab.land",
"developer.collab.land",
"developers.collab.land",

**Comment by iSpeakNerd** [comment]
> We can also deploy this same content to help.collab.land since it's already deployed to multiple domains: "docs.collab.land", "doc.collab.land", "dev.collab.land", "developer.collab.land", "developers.collab.land",

i'll let you two handle that! 🤣

**Pull request closed without merging**
