### PR TITLE
Re-Organize Docs and Add Python Mini-App Template

### PR DESCRIPTION
**Pull request by kenny-io**

### CODE REVIEW

**Comment by kenny-io** [comment]
A key consideration here is that this PR will break incoming links which could potentially hurt our SEO. If it's possible, we should set up redirects:
[from docs/upstream-integrations/build-a-miniapp.md to docs/upstream-integrations/getting-started.md] AND 
[from docs/upstream-integrations/test-locally.md to docs/upstream-integrations/customize-collab-actions.md

cc @uniyalabhishek

**Comment by uniyalabhishek** [comment]
@kenny-io wouldn’t it be `docs/upstream-integrations/collab-actions/getting-started` ? key consideration, a new folder collab-actions and no `.md` at the end

**Comment by kenny-io** [comment]
@uniyalabhishek yeah we don't need an index file for it since Docusaurus already provides collection of folders in that route. Also yes, this path is correct `docs/upstream-integrations/collab-actions/getting-started` as well as the second one `docs/upstream-integrations/collab-actions/customize-collab-actions`

**Comment by uniyalabhishek** [comment]
@kenny-io Merging this PR now. Thank you! I will create a new PR for the redirect

**Review by uniyalabhishek — APPROVED** [review]

**Comment by uniyalabhishek** [comment]
@kenny-io @raymondfeng We are receiving complaints from devs that old docs link we had shared earlier are broken. It's maybe hurting our SEO as well.
Mostly: docs/upstream-integrations/build-a-miniapp.md & docs/upstream-integrations/test-locally.md

We need to set redirects to updated docs to https://dev.collab.land/docs/upstream-integrations/collab-actions/getting-started-with-collab-actions & https://dev.collab.land/docs/upstream-integrations/collab-actions/customize-collab-actions

We have 2 options to fix this and set redirects.

1. On Front-end: using https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects
 but this doc suggests that it's best practice to set redirects on the backend

2. On Back-end: Since we are using AWS Amplify to host dev.collab.land. It looks like Amplify does supports redirect: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html
@raymondfeng If possible, can you please add it for 2 docs I shared?

**Comment by kenny-io** [comment]
I fixed this by configuring redirects on the Developer Site on Amplify, all
old links should be redirecting to the new URL

**Pull request merged**
